config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'ideas#index'
  resources :ideas
  get 'about' => 'static_pages#about'
  get 'random' => 'static_pages#random'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/idea.rb
class Idea < ApplicationRecord
	validates :description, :author ,presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
	def index
		@ideas = Idea.order("created_at DESC").paginate(:page => params[:page], :per_page => 3)

	end	
	def create
		@ideas = Idea.create(idea_params)
		if @ideas.valid?
			#implemeant later
		else
			#implement later
		end		
		redirect_to root_path

	end	
	def edit
		@ideas = Idea.find(params[:id])
	end	
	def update
		@ideas = Idea.find(params[:id])
		if @ideas.update(idea_params)
			redirect_to root_path
		else
			redirect_to edit_idea_path
		end		
	end	
	def destroy
		@ideas = Idea.find(params[:id])
		@ideas.destroy
		redirect_to root_path
	end		
	private
	def idea_params
		params.require(:idea).permit(:description,:author)

	end	
	
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
	def about
	end
	def random
		@ideas = Idea.order("RANDOM()").first
	end	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ideas_helper.rb
module IdeasHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/ideas/edit.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Edit</title>
</head>
<body>
	<h1>Revise Ideas</h1>
	<%= simple_form_for @ideas, method: :patch do |f| %>
		<%= f.input :description %>
		<%= f.input :author %>
		<%= f.submit 'Submit' , class: 'btn btn-primary' %>
	<% end %>	
</body>
</html>

app/views/ideas/index.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Ideator</title>
</head>
<body>
	<button type="button" class="btn btn-primary btn-lg btn_idea" data-toggle="modal" data-target="#myModal">
  Add Ideas
</button>


<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span></button>
        <h4 class="modal-title" id="myModalLabel">Generate Your Ideas</h4>
      </div>
      <div class="modal-body">
       	<%= simple_form_for Idea.new do |f| %>
  <%= f.input :description %>
  <%= f.input :author %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <%= f.submit 'Submit', class: 'btn btn-primary' %>
      </div>
      <% end %>
    </div>
  </div>
</div>
	<% @ideas.each do|idea| %>
			<div class = "panel panel-default">
			<div class="panel-body">
				<blockquote>
				<p> <%= idea.description %></p>
				<small> <%= idea.author %> </small>
			</blockquote>
			<div class="btn-group" role="group">
				<%= link_to 'Delete', idea_path(idea), method: :delete, class: 'btn btn-sm btn-danger', data: {confirm: "Are you sure?"} %>
        <%= link_to 'Update', edit_idea_path(idea), class: 'btn btn-sm btn-success' %>
      </div>

			</div>	
		</div>	
	<% end %>	
	<div class="text-center">
		<%= will_paginate @ideas %>
	</div>	
</body>
</html>
        

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AppName</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Dosis|Open+Sans" rel="stylesheet">
  </head>

  <body>
      <div id="wrapper">
  	     <%= render 'shared/navbar' %>
            <div class="container">
	             <%= yield %>
            </div>
      </div>
      <div class="container">
          <%= render 'shared/footer' %>
       </div> 
  </body>
</html>

app/views/shared/_footer.html.erb
<div class="footer text-center">
	<div class="container">
	<p>© TECHRISE <%=Date.today.year %> All Rights Reserverd</p>
	</div>
</div>	

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default">
  		<div class="container-fluid">
    		<div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#mynavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span> 
      </button>
      			<a class="navbar-brand" href="/ideas">Ideator</a>
    		</div>
        <div class="collapse navbar-collapse" id="mynavbar">
        <ul class="nav navbar-nav navbar-right">
            <li><%= link_to 'About', about_path %></li>
            <li><%= link_to 'All Ideas', root_path %></li>
            <li><%= link_to 'Random Ideas',random_path %></li>
          </ul>  

    
  		</div>
	</nav>

app/views/static_pages/about.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>About Page</title>
</head>
<body>
	<h1>About</h1>

<h4>Share your ideas with the world and find others.</h4>

<p>
  Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
  tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
  quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
  consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
  cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
  proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
</p>

<p>
  Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
  tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
  quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
  consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
  cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
  proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
</p>

<p>
  Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
  tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
  quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
  consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
  cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
  proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
</p>
</body>
</html>

app/views/static_pages/random.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Random Ideas</title>
</head>
<body>
	<%= link_to 'Inspire me',random_path,class: 'btn btn-sm btn-primary' %></button>


      <div class="panel panel-default" style="margin-top:10px;">
      	<div class="panel-body">
      		<blockquote>
      			<p><%= @ideas.description %></p>
      			<small><%= @ideas.author %></small>
      		</blockquote>		
      <div class="btn-group" role="group">
      		<%= link_to 'Delete', idea_path(@ideas) , method: :delete , class: 'btn btn-sm btn-danger',data:{confirm:"Are you Sure?"} %>
      		<%= link_to 'Update',edit_idea_path(@ideas),class: 'btn btn-sm btn-success' %>
      </div>	
      	</div>
      </div>			
</body>
</html>